### ISSUE TITLE
HDF5 error in deepmaps docker demo

### ISSUE THREAD

**Issue by adamtongji** [OSU-BMBL/deepmaps#5]
Hi, 
Thank you for your great tool! I just met a problem when running the docker demo script. In the docker container, the test.r script could not load the lymph node h5 file, with the error report as following:
<img width="849" alt="截屏2022-05-24 上午11 32 28" src="https://user-images.githubusercontent.com/13899771/169943494-05481933-e254-4ffb-a11d-befa7c08cff2.png">

Can you help us solve this issue?
Thanks,
Shaliu

**Comment by chthub** [comment]
@adamtongji Hi, have you run the `test.sh` first? The `test.sh` will automatically download the h5 file and invoke `test.r`. If you directly run `test.r`, it may have authority problem. Could you please check if there is any files in `/deepmaps/docker/data/`. If the folder is emply, please run` test.sh`. Thanks.

**Comment by adamtongji** [comment]
Thank you for your reply! 

The "wget" command failed due to the network accessibility problem. I downloaded the two demo files locally and then mount the files into the docker container, and then worked~

Thank you again for your help!

**Comment by adamtongji** [comment]
Thank you for your help!  We solved this `h5` problem by manually download before docker test.sh script.

But we did not complete the `test.sh` and met the error reported below(after less than 1hr running):

<img width="595" alt="截屏2022-05-31 上午9 37 29" src="https://user-images.githubusercontent.com/13899771/171076321-df165685-fb20-411a-a59b-fb99656fa611.png">
<img width="533" alt="截屏2022-05-31 上午9 45 01" src="https://user-images.githubusercontent.com/13899771/171076629-f9094e26-2e94-41cd-8e43-e492b0c9f132.png">


<img width="634" alt="截屏2022-05-31 上午9 37 38" src="https://user-images.githubusercontent.com/13899771/171076342-f588be37-ac0d-4f5e-aeba-ca84ca67bfc1.png">

The GPU of our server is 3090, which might support the cuda11 in the docker environment. 
Can your help us to solve the issue above?
Thanks,
Shaliu

**Comment by chthub** [comment]
@adamtongji Similar to [this](https://github.com/pyg-team/pytorch_geometric/issues/2831#issue-939447237). Is your pytorch version=1.7 and cuda version=11.0?  Upgrading pytorch to 1.8 and cuda to 11.1 should help.

**Comment by adamtongji** [comment]
> @adamtongji Similar to [this](https://github.com/pyg-team/pytorch_geometric/issues/2831#issue-939447237). Is your pytorch version=1.7 and cuda version=11.0? Upgrading pytorch to 1.8 and cuda to 11.1 should help.

I am using the docker image to run the `test.sh` as your tutorial. The version of pytorch is 1.7.0 in the docker image. And I am not sure the cuda version in the docker image environment, as the cudatoolkit seems to be 11.5? 

Does it mean that I should reinstall `pytorch` and `cuda` in the `docker container` and update the origin `docker image`? And will the reinstall of pytorch and cuda influence other dependencies in the docker environment?

**Comment by chthub** [comment]
@adamtongji Yes, the default PyTorch version available doesn’t support GeForce Ampere cards out of the box. So you neeed to update pytorch and cuda manually. Thank you for pointing out this problem. We will also update the docker image later.
